package theme

import "github.com/charmbracelet/lipgloss"

var (
	TitleStyle             = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("230")).Background(lipgloss.Color("24"))
	HeaderStyle            = lipgloss.NewStyle().Padding(0, 1)
	FooterStyle            = lipgloss.NewStyle().Foreground(lipgloss.Color("250"))
	SidebarStyle           = lipgloss.NewStyle()
	WorkspaceStyle         = lipgloss.NewStyle()
	SectionTitleStyle      = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("81"))
	SectionDividerStyle    = lipgloss.NewStyle().Foreground(lipgloss.Color("238"))
	SectionBodyStyle       = lipgloss.NewStyle()
	PanelBodyStyle         = lipgloss.NewStyle().Foreground(lipgloss.Color("252"))
	TitleRowStyle          = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("117"))
	BorderStyle            = lipgloss.NewStyle().Foreground(lipgloss.Color("240"))
	CopyModalBorderStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("208"))
	CopyModalTitleStyle    = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("208"))
	CopyModalMutedStyle    = lipgloss.NewStyle().Foreground(lipgloss.Color("215"))
	HelpScopeStyle         = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("81"))
	HelpActionStyle        = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("221"))
	HelpTextStyle          = lipgloss.NewStyle().Foreground(lipgloss.Color("252"))
	MetaLabelStyle         = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("245"))
	AccentStyle            = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("117"))
	MutedStyle             = lipgloss.NewStyle().Foreground(lipgloss.Color("245"))
	OKStyle                = lipgloss.NewStyle().Foreground(lipgloss.Color("78"))
	WarnStyle              = lipgloss.NewStyle().Foreground(lipgloss.Color("221"))
	ErrorStyle             = lipgloss.NewStyle().Foreground(lipgloss.Color("203"))
	OldFormatBadgeStyle    = ErrorStyle
	SaveSelectorArrowStyle = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("81"))
	NavItemStyle           = lipgloss.NewStyle().Foreground(lipgloss.Color("252"))
	NavActiveStyle         = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("230"))
	NavFocusStyle          = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("230")).Background(lipgloss.Color("31"))
	ModalBoxStyle          = lipgloss.NewStyle().Border(lipgloss.DoubleBorder()).BorderForeground(lipgloss.Color("81")).Padding(1, 2).Background(lipgloss.Color("236")).Foreground(lipgloss.Color("230"))
	ButtonStyle            = lipgloss.NewStyle().Foreground(lipgloss.Color("81"))
	ButtonActiveStyle      = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("230")).Background(lipgloss.Color("24"))
	ButtonFocusStyle       = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("230")).Background(lipgloss.Color("31"))
	CursorStyle            = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("117"))
	SelectedStyle          = lipgloss.NewStyle().Foreground(lipgloss.Color("78"))
	FocusStyle             = lipgloss.NewStyle().Foreground(lipgloss.Color("221"))
)
